<?php

require 'fedora_user_switch.php';

use Drupal\taxonomy\Entity\Term;

$term_uri_map = [
    "Aerial views" => "http://id.worldcat.org/fast/1423687",
    "Animals" => "http://id.worldcat.org/fast/809468",
    "Apartments" => "http://id.worldcat.org/fast/811207",
    "Automobiles" => "http://id.worldcat.org/fast/823232",
    "Billboards" => "http://id.worldcat.org/fast/831786",
    "Building" => "http://id.worldcat.org/fast/840551",
    "Buildings" => "http://id.worldcat.org/fast/840962",
    "Businesspeople" => "http://id.worldcat.org/fast/842980",
    "Casinos" => "http://id.worldcat.org/fast/848246",
    "Cities and towns" => "http://id.worldcat.org/fast/861748",
    "Commercial buildings" => "http://id.worldcat.org/fast/869373",
    "Construction equipment" => "http://id.worldcat.org/fast/875912",
    "Construction workers" => "http://id.worldcat.org/fast/876155",
    "Electric lines" => "http://id.worldcat.org/fast/905095",
    "Electric signs" => "http://id.worldcat.org/fast/905895",
    "Escalators" => "http://id.worldcat.org/fast/915111",
    "Express highways" => "http://id.worldcat.org/fast/918809",
    "Flags" => "http://id.worldcat.org/fast/926942",
    "Flood control" => "http://id.worldcat.org/fast/927443",
    "Historic sites" => "http://id.worldcat.org/fast/957846",
    "Hotels" => "http://id.worldcat.org/fast/961767",
    "Housing development" => "http://id.worldcat.org/fast/962394",
    "Land settlement" => "http://id.worldcat.org/fast/991305",
    "Land use" => "http://id.worldcat.org/fast/991472",
    "Lightning" => "http://id.worldcat.org/fast/998677",
    "Moon" => "http://id.worldcat.org/fast/1240375",
    "Mountains" => "http://id.worldcat.org/fast/1028366",
    "Neighborhoods" => "http://id.worldcat.org/fast/1715963",
    "Neon signs" => "http://id.worldcat.org/fast/1035830",
    "Pedestrian areas" => "http://id.worldcat.org/fast/1056361",
    "Pedestrians" => "http://id.worldcat.org/fast/1056380",
    "Real estate development" => "http://id.worldcat.org/fast/1090973",
    "Resorts" => "http://id.worldcat.org/fast/1095631",
    "Roads" => "http://id.worldcat.org/fast/1098511",
    "Scenic overlooks" => "http://id.worldcat.org/fast/1747088",
    "Sculpture" => "http://id.worldcat.org/fast/1109483",
    "Signs and symbols" => "http://id.worldcat.org/fast/1118355",
    "Streets" => "http://id.worldcat.org/fast/1134794",
    "Towers" => "http://id.worldcat.org/fast/1153279",
    "Traffic signs and signals" => "http://id.worldcat.org/fast/1154277",
    "Trails" => "http://id.worldcat.org/fast/1154418",
    "Views" => "http://id.worldcat.org/fast/1166896",
    "Water" => "http://id.worldcat.org/fast/1171139",
    "Waterworks" => "http://id.worldcat.org/fast/1172798",
    "Weather" => "http://id.worldcat.org/fast/1173087",
    "Advertising" => "http://id.worldcat.org/fast/797511",
    "Airplanes" => "http://id.worldcat.org/fast/803053",
    "Airports" => "http://id.worldcat.org/fast/803726",
    "Alleys" => "http://id.worldcat.org/fast/805585",
    "Amusement rides" => "http://id.worldcat.org/fast/808097",
    "Apartment houses" => "http://id.worldcat.org/fast/811132",
    "Art" => "http://id.worldcat.org/fast/815177",
    "Art--Reproduction" => "http://id.worldcat.org/fast/815325",
    "Automobile dealers" => "http://id.worldcat.org/fast/822818",
    "Automobile driving" => "http://id.worldcat.org/fast/822899",
    "Baptist church buildings" => "http://id.worldcat.org/fast/827271",
    "Barbershops" => "http://id.worldcat.org/fast/827454",
    "Beds" => "http://id.worldcat.org/fast/829528",
    "Bicycles" => "http://id.worldcat.org/fast/831489",
    "Birds" => "http://id.worldcat.org/fast/832970",
    "Bowling alleys" => "http://id.worldcat.org/fast/837248",
    "Bridges" => "http://id.worldcat.org/fast/838671",
    "Bridges--Design and construction" => "http://id.worldcat.org/fast/838690",
    "Building materials" => "http://id.worldcat.org/fast/840723",
    "Buildings--Deterioration" => "http://id.worldcat.org/fast/841002",
    "Buses" => "http://id.worldcat.org/fast/842142",
    "Business enterprises" => "http://id.worldcat.org/fast/842519",
    "Catholic church buildings" => "http://id.worldcat.org/fast/849149",
    "Church buildings" => "http://id.worldcat.org/fast/860599",
    "Clouds" => "http://id.worldcat.org/fast/864856",
    "Clubs" => "http://id.worldcat.org/fast/864940",
    "Coffeehouses" => "http://id.worldcat.org/fast/866407",
    "Coins" => "http://id.worldcat.org/fast/866649",
    "County government" => "http://id.worldcat.org/fast/881490",
    "Cows" => "http://id.worldcat.org/fast/882039",
    "Deserts" => "http://id.worldcat.org/fast/891230",
    "Dining rooms" => "http://id.worldcat.org/fast/893926",
    "Dirt roads" => "http://id.worldcat.org/fast/1728432",
    "Dogs" => "http://id.worldcat.org/fast/896265",
    "Droughts" => "http://id.worldcat.org/fast/898449",
    "Entertainers" => "http://id.worldcat.org/fast/912655",
    "Fast food restaurants" => "http://id.worldcat.org/fast/921665",
    "Fire stations" => "http://id.worldcat.org/fast/925546",
    "Fireworks" => "http://id.worldcat.org/fast/1198494",
    "Fishing" => "http://id.worldcat.org/fast/926650",
    "Floods" => "http://id.worldcat.org/fast/927573",
    "Football" => "http://id.worldcat.org/fast/931446",
    "Footbridges" => "http://id.worldcat.org/fast/931454",
    "Gasoline pumps" => "http://id.worldcat.org/fast/938777",
    "Golf" => "http://id.worldcat.org/fast/944659",
    "Golfers" => "http://id.worldcat.org/fast/944774",
    "Graffiti" => "http://id.worldcat.org/fast/945846",
    "Grasses" => "http://id.worldcat.org/fast/946724",
    "Historical markers" => "http://id.worldcat.org/fast/958139",
    "House furnishings" => "http://id.worldcat.org/fast/961974",
    "Industrial buildings" => "http://id.worldcat.org/fast/970853",
    "Lakes" => "http://id.worldcat.org/fast/990901",
    "Land subdivision" => "http://id.worldcat.org/fast/991346",
    "Landforms" => "http://id.worldcat.org/fast/991689",
    "Landscapes" => "http://id.worldcat.org/fast/1735625",
    "Libraries" => "http://id.worldcat.org/fast/997341",
    "Limousines" => "http://id.worldcat.org/fast/998974",
    "Lodging-houses" => "http://id.worldcat.org/fast/1001859",
    "Marinas" => "http://id.worldcat.org/fast/1009319",
    "Mobile homes" => "http://id.worldcat.org/fast/1024249",
    "Monorail railroads" => "http://id.worldcat.org/fast/1025698",
    "Monuments" => "http://id.worldcat.org/fast/1025892",
    "Mormon Church" => "http://id.worldcat.org/fast/1026221",
    "Motels" => "http://id.worldcat.org/fast/1026838",
    "Mountaineering" => "http://id.worldcat.org/fast/1028334",
    "Office buildings" => "http://id.worldcat.org/fast/1044055",
    "Palms" => "http://id.worldcat.org/fast/1051793",
    "Parking garages" => "http://id.worldcat.org/fast/1053655",
    "Parking lots" => "http://id.worldcat.org/fast/1053672",
    "Parks" => "http://id.worldcat.org/fast/1053705",
    "People" => "http://id.worldcat.org/fast/1058861",
    "Plants" => "http://id.worldcat.org/fast/1065823",
    "Playgrounds" => "http://id.worldcat.org/fast/1066996",
    "Police" => "http://id.worldcat.org/fast/1068398",
    "Portraits" => "http://id.worldcat.org/fast/1072324",
    "Prefabricated houses" => "http://id.worldcat.org/fast/1075051",
    "Public utilities" => "http://id.worldcat.org/fast/1083130",
    "Railroad tracks" => "http://id.worldcat.org/fast/1431160",
    "Railroads" => "http://id.worldcat.org/fast/1088711",
    "Real estate business" => "http://id.worldcat.org/fast/1090898",
    "Recreation" => "http://id.worldcat.org/fast/1091713",
    "Reflection (Optics)" => "http://id.worldcat.org/fast/1092485",
    "Reinforced concrete construction" => "http://id.worldcat.org/fast/1093465",
    "Restaurants" => "http://id.worldcat.org/fast/1095907",
    "Roads--Design and construction" => "http://id.worldcat.org/fast/1098548",
    "Rocks" => "http://id.worldcat.org/fast/1099409",
    "Roofs" => "http://id.worldcat.org/fast/1100315",
    "Rooms" => "http://id.worldcat.org/fast/1100369",
    "School buses" => "http://id.worldcat.org/fast/1107107",
    "School children" => "http://id.worldcat.org/fast/1107147",
    "School facilities" => "http://id.worldcat.org/fast/1107385",
    "Schools" => "http://id.worldcat.org/fast/1107958",
    "Shopping centers" => "http://id.worldcat.org/fast/1116908",
    "Sidewalks" => "http://id.worldcat.org/fast/1118160",
    "Signs and signboards" => "http://id.worldcat.org/fast/1118336",
    "Skaters" => "http://id.worldcat.org/fast/1119895",
    "Skyscrapers" => "http://id.worldcat.org/fast/1120291",
    "Snow" => "http://id.worldcat.org/fast/1121907",
    "Sprinklers" => "http://id.worldcat.org/fast/1130962",
    "Storefronts" => "http://id.worldcat.org/fast/1134038",
    "Stores, Retail" => "http://id.worldcat.org/fast/1134043",
    "Storms" => "http://id.worldcat.org/fast/1134142",
    "Street lighting" => "http://id.worldcat.org/fast/1134687",
    "Surveying" => "http://id.worldcat.org/fast/1139579",
    "Surveying--Equipment and supplies" => "http://id.worldcat.org/fast/1139587",
    "Surveyors" => "http://id.worldcat.org/fast/1139621",
    "Swimmers" => "http://id.worldcat.org/fast/1140322",
    "Swimming pools" => "http://id.worldcat.org/fast/1140385",
    "Tourists" => "http://id.worldcat.org/fast/1153237",
    "Trees" => "http://id.worldcat.org/fast/1155984",
    "Urban renewal" => "http://id.worldcat.org/fast/1162536",
    "Warehouses" => "http://id.worldcat.org/fast/1170760",
    "Water use" => "http://id.worldcat.org/fast/1172188",
    "Water--Pollution" => "http://id.worldcat.org/fast/1171279",
    "Watersheds" => "http://id.worldcat.org/fast/1172744",
    "Water-supply" => "http://id.worldcat.org/fast/1172350",
    "Wild flowers" => "http://id.worldcat.org/fast/1175085",
    "Wooden-frame buildings" => "http://id.worldcat.org/fast/1179732",
    "Abandoned buildings" => "http://id.worldcat.org/fast/1740987",
    "Aerial photographs" => "http://id.worldcat.org/fast/798077",
    "Bodies of water" => "http://id.worldcat.org/fast/835302",
    "Landscape photography" => "http://id.worldcat.org/fast/992030",
    "Portrait photography--Posing" => "http://id.worldcat.org/fast/1072264",
    "Railroad rails" => "http://id.worldcat.org/fast/1431130",
    "Rainbows" => "http://id.worldcat.org/fast/1759364",
    "Stadiums" => "http://id.worldcat.org/fast/1131272",
    "Wheels" => "http://id.worldcat.org/fast/1174522",
];

$term_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
$iu = \Drupal::service('islandora.utils');
foreach($term_uri_map as $term_label => $uri) {
    if ($existing_uri_term = $iu->getTermForUri($uri)) { print("Already have term ({$existing_uri_term->label()}) for uri $uri\n"); continue; }

    if ($term = reset($term_storage->loadByProperties(['vid' => 'subject','name' => $term_label]))) {
        print("Found term '{$term_label}' ({$term->id()})\t");
    } else {
        print("Making new term '{$term_label}'\t");
        $term = Term::create(['vid' => 'subject', 'name' => $term_label]);
    }
    $term->field_authority_link[] = ['source'=>'fast', 'uri' => $uri];
    try {
        $term->save();
        print("saved term {$term->label()} with uri $uri\n");
    } catch (Exception $e) {
        print("could not save term {$term->label()} with uri $uri\n");
    }
}
